"""add source column that shows us who made this task

Revision ID: 04478dab9d9b
Revises: d5e5b5804c05
Create Date: 2026-01-27 14:13:26.384159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04478dab9d9b'
down_revision: Union[str, Sequence[str], None] = 'd5e5b5804c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "tasks",
    sa.Column(
        "source",
        sa.String(length=20),
        nullable=False,
        server_default="user"
    )
)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'source')
    # ### end Alembic commands ###
