"""update task table make last_updated column default func.now()

Revision ID: 1a9aa32751f9
Revises: 98f7f42e270c
Create Date: 2026-01-28 13:03:06.826569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9aa32751f9'
down_revision: Union[str, Sequence[str], None] = '98f7f42e270c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
