"""add is_arvhieved column to tasks

Revision ID: 1ff7ea01d22d
Revises: bc89a197fbd3
Create Date: 2026-02-04 15:59:57.366742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff7ea01d22d'
down_revision: Union[str, Sequence[str], None] = 'bc89a197fbd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_archived')
    # ### end Alembic commands ###
