"""add users and user_id to tasks

Revision ID: 7cdf16ccb7e2
Revises: 1eab802d422c
Create Date: 2026-01-26 17:58:13.971443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cdf16ccb7e2'
down_revision: Union[str, Sequence[str], None] = '1eab802d422c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.alter_column('task_time_logs', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_time_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('one_active_timer_global'), table_name='task_time_logs', postgresql_where='(ended_at IS NULL)')
    op.drop_index(op.f('one_active_timer_per_task'), table_name='task_time_logs', postgresql_where='(ended_at IS NULL)')
    op.drop_index(op.f('uniq_active_task_timer'), table_name='task_time_logs', postgresql_where='(ended_at IS NULL)')
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.create_index(op.f('uniq_active_task_timer'), 'task_time_logs', ['task_id'], unique=True, postgresql_where='(ended_at IS NULL)')
    op.create_index(op.f('one_active_timer_per_task'), 'task_time_logs', ['task_id'], unique=True, postgresql_where='(ended_at IS NULL)')
    op.create_index(op.f('one_active_timer_global'), 'task_time_logs', [sa.literal_column('(ended_at IS NULL)')], unique=True, postgresql_where='(ended_at IS NULL)')
    op.alter_column('task_time_logs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('task_time_logs', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('users')
    # ### end Alembic commands ###
