"""update task table make last_updated column default func.now()

Revision ID: 8588988509e5
Revises: 3fcb0f2157bd
Create Date: 2026-01-28 13:17:15.323791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8588988509e5'
down_revision: Union[str, Sequence[str], None] = '3fcb0f2157bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
