"""add users and user_id to tasks

Revision ID: 8da3a4cf2c05
Revises: 7cdf16ccb7e2
Create Date: 2026-01-26 18:23:30.314601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da3a4cf2c05'
down_revision: Union[str, Sequence[str], None] = '7cdf16ccb7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
