"""add streak fields to user

Revision ID: bc89a197fbd3
Revises: 8588988509e5
Create Date: 2026-02-03 19:16:18.023693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc89a197fbd3'
down_revision: Union[str, Sequence[str], None] = '8588988509e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_activity_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'last_activity_date')
    # ### end Alembic commands ###
