"""update task table make last_updated column default func.now()

Revision ID: d0902f82e5ae
Revises: 1a9aa32751f9
Create Date: 2026-01-28 13:03:49.688835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0902f82e5ae'
down_revision: Union[str, Sequence[str], None] = '1a9aa32751f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
