"""add codewars_username column to users

Revision ID: d5e5b5804c05
Revises: 8da3a4cf2c05
Create Date: 2026-01-27 13:45:00.812994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e5b5804c05'
down_revision: Union[str, Sequence[str], None] = '8da3a4cf2c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('codewars_username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['codewars_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'codewars_username')
    # ### end Alembic commands ###
