"""add codewars_completed table

Revision ID: f0e951f21e64
Revises: 04478dab9d9b
Create Date: 2026-01-27 18:06:10.736455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e951f21e64'
down_revision: Union[str, Sequence[str], None] = '04478dab9d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codewars_completed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('code_wars_task_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code_wars_task_id', name='uq_user_codewars_kata')
    )
    op.add_column('users', sa.Column('codewars_last_completed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'codewars_last_completed')
    op.drop_table('codewars_completed')
    # ### end Alembic commands ###
